Display:   1. Optimize settings for 24" FHD display.   2. Add support for refresh rate changes (e.g. 144Hz display).   3. Allow brightness to go below 0 by decreasing contrast.   4. When brightness goes below 0, contrast value will also be shown on i3blocks.

diff --git a/ubuntu/.local/lib/bash/external-monitor-control b/ubuntu/.local/lib/bash/external-monitor-control
--- a/ubuntu/.local/lib/bash/external-monitor-control
+++ b/ubuntu/.local/lib/bash/external-monitor-control
@@ -17,11 +17,17 @@ if [ $is_reading_mode = true ]; then
     mode="reading"
     brightness=$reading_brightness
     temperature=$color_temperature_reading
+    contrast=$reading_contrast
 else
     mode="video"
     brightness=$video_brightness
     temperature=$color_temperature_video
+    contrast=$video_contrast
 fi
+
+display-mode() {
+    [[ $mode = "video" ]] && echo "Video" || echo "Reading"
+}
 
 case "$1" in
     b)
@@ -29,30 +35,73 @@ case "$1" in
         # TODO: Add retry limit
         while true; do
             output=`ddcutil getvcp $brightness_feature_id --bus $i2c_bus | gawk '{print $9}' | sed 's/,//' | tail -1`
-            if [[ $output == ?(-)+([0-9]) ]]; then
-                echo $output
-                exit 0
+            contrast=`ddcutil getvcp $contrast_feature_id --bus $i2c_bus | gawk '{print $9}' | sed 's/,//' | tail -1`
+            if [[ $output == ?(-)+([0-9]) ]] && [[ $contrast == ?(-)+([0-9]) ]]; then
+                if [[ $contrast != "50" ]]; then
+                    output="$output | $contrast"
+                fi
+                break
+            else
+                sleep 2
             fi
-            sleep 2
         done
+        echo $output
+        display-mode
+        exit 0
         ;;
     bu)
-        let brightness="$brightness + $brightness_step"
-        if [ $brightness -gt 100 ]; then
-            brightness=100
+        if [ $brightness -eq 0 ] && [ $contrast -lt 50 ]; then
+            let contrast="$contrast + $contrast_step"
+            if [ $contrast -gt 50 ]; then
+                contrast=50
+            fi
+            ddcutil setvcp $contrast_feature_id $contrast --bus $i2c_bus
+            sed -i s/"$mode"_contrast=.*/"$mode"_contrast=$contrast/ $rc
+        else
+            let brightness="$brightness + $brightness_step"
+            if [ $brightness -gt 100 ]; then
+                brightness=100
+            fi
+            ddcutil setvcp $brightness_feature_id $brightness --bus $i2c_bus
+            sed -i s/"$mode"_brightness=.*/"$mode"_brightness=$brightness/ $rc
         fi
-		ddcutil setvcp $brightness_feature_id $brightness --bus $i2c_bus
-        sed -i s/"$mode"_brightness=.*/"$mode"_brightness=$brightness/ $rc
-        echo $brightness
+
+        display-mode
+        if [[ $contrast == "50" ]]; then
+            echo "$brightness"
+        else
+            echo "$brightness | $contrast"
+        fi
+        echo "B: $brightness   C: $contrast"
         ;;
     bd)
-        let brightness="$brightness - $brightness_step"
-        if [ $brightness -lt 0 ]; then
-            brightness=0
+        if [ $brightness -le 0 ]; then
+            set +e # NOTE: In Bash 5.0.3 (Ubuntu 19.10), If expression evaluated to 0, it results expression failure and quit execution due to "-e".
+            let contrast="$contrast - $contrast_step"
+            set -e
+            if [ $contrast -lt 0 ]; then
+                contrast=0
+            fi
+            ddcutil setvcp $contrast_feature_id $contrast --bus $i2c_bus
+            sed -i s/"$mode"_contrast=.*/"$mode"_contrast=$contrast/ $rc
+        else
+            set +e # NOTE: In Bash 5.0.3 (Ubuntu 19.10), If expression evaluated to 0, it results expression failure and quit execution due to "-e".
+            let brightness="$brightness - $brightness_step"
+            set -e
+            if [ $brightness -lt 0 ]; then
+                brightness=0
+            fi
+            ddcutil setvcp $brightness_feature_id $brightness --bus $i2c_bus
+            sed -i s/"$mode"_brightness=.*/"$mode"_brightness=$brightness/ $rc
         fi
-		ddcutil setvcp $brightness_feature_id $brightness --bus $i2c_bus
-        sed -i s/"$mode"_brightness=.*/"$mode"_brightness=$brightness/ $rc
-        echo $brightness
+
+        display-mode
+        if [[ $contrast == "50" ]]; then
+            echo "$brightness"
+        else
+            echo "$brightness | $contrast"
+        fi
+        echo "B: $brightness   C: $contrast"
         ;;
     bs)
         if [ $mode = "reading" ]; then
@@ -60,9 +109,15 @@ case "$1" in
         else
             isReadingMode="false"
         fi
-		ddcutil setvcp $brightness_feature_id $brightness --bus $i2c_bus
-		ddcutil setvcp $color_temperature_feature_id $temperature --bus $i2c_bus
+		ddcutil setvcp $color_temperature_feature_id $temperature $brightness_feature_id $brightness $contrast_feature_id $contrast --bus $i2c_bus
+
+        display-mode
         sed -i s/is_reading_mode=.*/is_reading_mode="$isReadingMode"/ $rc
-        echo $brightness
+        if [[ $contrast == "50" ]]; then
+            echo "$brightness"
+        else
+            echo "$brightness | $contrast"
+        fi
+        echo "B: $brightness   C: $contrast"
         ;;
 esac
